/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Duck(props) {
    
    const duckRef = useRef(null)
    const duck = useGLTF("/static/Duck.glb");

    return (
        <primitive 
            object={duck.scene}
            ref={duckRef}
            {...props} 
            dispose={null} 
            onClick={(e)=>{
                console.log(e.object.name)
                e.stopPropagation()
    
            }}
        />
        
    );
}

useGLTF.preload("/static/Duck.glb");